""" To build the image execute the following command from the parent docker directory
docker build -t some_tag -f docker/Dockerfile . 
"""

FROM analysiscenter1/ds-py3:cpu
MAINTAINER Roman Kh <rhudor@gmail.com>

COPY . /notebooks/Seismicpro
